@echo off
(
MD "%CWD%plugins\programs\Addons4Xbox Installer\resources\media"
MD "%CWD%skin\Confluence\scripts"
MD "%CWD%skin\Confluence Lite\language\Ukrainian"
MD "%CWD%web\xbmciphone\iphone"
MD "%CWD%web\xbmciphone\thumbs"
MD "%CWD%xbmc\cores\DllLoader\Debug"
MD "%CWD%xbmc\cores\DllLoader\Release"
MD "%CWD%xbmc\cores\dvdplayer\Codecs\ffmpeg\patches\ffmpeg-upstream"
MD "%CWD%xbmc\cores\dvdplayer\Codecs\ffmpeg\patches\ours\unused"
MD "%CWD%xbmc\guilib\Release"
MD "%CWD%xbmc\lib\libapetag\Release"
MD "%CWD%xbmc\lib\libcurl\release"
MD "%CWD%xbmc\lib\libFileZilla\Release"
MD "%CWD%xbmc\lib\libhts\Win32\Release"
MD "%CWD%xbmc\lib\libsmb\libsamba\source\bin"
MD "%CWD%xbmc\lib\libUPnP\Neptune\Build\Scripts"
MD "%CWD%xbmc\lib\libUPnP\Platinum\Build\Scripts"
MD "%CWD%xbmc\lib\libUPnP\Platinum\Build\Targets\mipsel-psp-linux\CodeWarrior\Platinum_Data\Build_All"
MD "%CWD%xbmc\lib\libUPnP\Platinum\ThirdParty"
MD "%CWD%xbmc\lib\libUPnP\Release"
MD "%CWD%xbmc\lib\UnrarXLib\Release"
MD "%CWD%xbmc\music\karaoke"
) >NUL  2>NUL